### ISSUE TITLE
Описание

### ISSUE THREAD

**Issue by Vladimir855** [Noname400/BrainFlayerPY#1]
1 База паролей должна быть один пароль на строку в txt?
2 Блюм фильтр адресов обязательно делать? Если да то какие адреса подходят все или только на 1?
3 Поиск по эфиру, отдельно делать базу и запускать?
4 Какие зависимости по питону нужны?
5 Возможен запуск на ubuntu?
6 Конвертация адресов только в bip44?
Пока всё

**Comment by Noname400** [comment]
1.да. Это может быть слово или фраза
2. Обязательно. А счем сравнивать? Все адреса 1,3,bc1
3. Да, но для этого надо доработать программу.
4. Зависимости напишу.
5. Да
6. В брайне нет бип.,

**Comment by Vladimir855** [comment]
пробовал запустить методом тыка выдает ошибку
~/Desktop/BrainFlayerPY-main# python3 -B pybw.py -th 3 -db btc.bf -in 1.txt -m sha256 -bal
File ice_secp256k1.so not found
Traceback (most recent call last):
  File "pybw.py", line 14, in <module>
    import secp256k1_lib
  File "/root/Desktop/BrainFlayerPY-main/secp256k1_lib.py", line 91, in <module>
    ice.scalar_multiplication.argtypes = [ctypes.c_char_p, ctypes.c_char_p]   # pvk,ret
NameError: name 'ice' is not defined

Модуль secp256k1 ставил, если правильно понял нужно secp256k1.so а в проге только secp256k1_lib

**Comment by Noname400** [comment]
Добавил и обновил

**Comment by Vladimir855** [comment]
Desktop/BrainFlayerPY-main# python3 -B pybw.py -th 3 -db btc.bf -in 1.txt -m sha256 -bal
----------------------------------------------------------------------
Thank you very much: @iceland2k14 for his libraries!
----------------------------------------------------------------------
[I] Version: * PY-Brainflayer v0.0.1b *
[I] Total kernel of CPU: 32
[I] Used kernel: 3
[I] Work mode - sha256
[I] Database Bloom Filter: btc.bf
[I] Check balance BTC: On
----------------------------------------------------------------------
BF LOADED
GO LOADED SEMPLE
Caught KeyboardInterrupt, terminating workers
Traceback (most recent call last):
  File "pybw.py", line 191, in <module>
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pybw.py", line 214, in <module>
    pool.terminate()
NameError: name 'pool' is not defined

**Comment by Vladimir855** [comment]
напиши зависимости

**Comment by Noname400** [comment]
bitcoin
colorama
requests
bitcoin
mmh3

requirements.txt
добавил

**Comment by Vladimir855** [comment]
всё установил всё равно та же ошибка

**Comment by Vladimir855** [comment]
посмотри это так и должно быть 
![Screenshot_2022-06-11_07-16-18](https://user-images.githubusercontent.com/48643229/173177874-59d5c9b3-cd0c-4846-b24c-ac143d072c50.png)

**Comment by Noname400** [comment]
да .
 дай мне время проверить работу

**Comment by Vladimir855** [comment]
если интересно вот как работает htm full
![Screenshot_2022-06-11_07-28-26](https://user-images.githubusercontent.com/48643229/173178234-8b7dd9ea-ef1e-45c3-a878-62e84a78e357.png)

по 10 ядер бит 7 ядер эфир

**Comment by Noname400** [comment]
htm full , я вроде не выкладывал )))

**Comment by Noname400** [comment]
обновил, работает
![image](https://user-images.githubusercontent.com/74019756/173178579-efd073df-c81d-4697-b413-ebe0bcb094de.png)

**Comment by Vladimir855** [comment]
адреса 1,3,bc1 в блюм как сделать

**Comment by Vladimir855** [comment]
не мог бы объяснить принцип работы проги как всё происходит
для примера в словаре 500000 запустил и когда оно остановится?

**Comment by Noname400** [comment]
> адреса 1,3,bc1 в блюм как сделать

Можно использовать блюм от ханта.

**Comment by Noname400** [comment]
> не мог бы объяснить принцип работы проги как всё происходит для примера в словаре 500000 запустил и когда оно остановится?

Когда все переберет.
Он перебирает  sha256, двойной sha256, и sha3

**Comment by Noname400** [comment]
На выходе проверяет сжатые и не сжатые ключи.

**Comment by Vladimir855** [comment]
использовал блюм от HtM-Lite ошибка ice_secp256k1.dll просит переустановить, запускал на Win7 x32. Может быть из-за платформы х32?

**Comment by Noname400** [comment]
Все блюмы на 64 работают

**Comment by Noname400** [comment]
Разрядность имеет знаяенте

**Comment by Vladimir855** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/48643229/173226045-583dd5a5-8fb6-4056-8aff-7da8f911d95b.png)

разные блюмы пробовал

**Comment by Vladimir855** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/48643229/173226333-8063c1b3-a09b-47bd-91b7-3595b612a885.png)

**Comment by Noname400** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/48643229/173226045-583dd5a5-8fb6-4056-8aff-7da8f911d95b.png)
> 
> разные блюмы пробовал

Почему вы решили что ошибка?

**Comment by Noname400** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/48643229/173226333-8063c1b3-a09b-47bd-91b7-3595b612a885.png)

Вроде все верно

**Comment by Vladimir855** [comment]
по моему не пропустила адреса bc1
внизу error 769085

**Comment by Noname400** [comment]
А почему он должен их пропустить?

**Comment by Vladimir855** [comment]
> А почему он должен их пропустить?

Ладно пропустим это, верю на слово! Хотел кое о чём поговорить узнать твоё мнение, может в телеграмм написать

**Comment by Noname400** [comment]
Пиши. Я на связи
